### ISSUE TITLE
writeTRC not accounting for marker tabbing

### ISSUE THREAD

**Issue by peruvianox** [JonathanCamargo/MoCapTools#1]
Hey folks, 

Thanks for providing these codes to streamline data processing! Lindsey Trejo sent this to me and it seems to be really useful so far. I noticed an error in writeTRC.m where the original code didnt tab to account for the 3 position values for each marker (around line 65). I have corrected this to 
`
  markerCols = strjoin(markerNames,  '\t\t\t');
  text{4} = sprintf('Frame#\t Time\t %s', markerCols);
`
in my code and it seems to work great (so far). I hope this helps!

-Ricky Pimentel

**Comment by JonathanCamargo** [comment]
Thank you! this is now incorporated in writeTRC.
